#ifndef _USB_UPGRADE_ERR_CODE_
#define _USB_UPGRADE_ERR_CODE_
//This file contains error code definitions of possible errors that can be generated by the upgrade code.

//No error
#define ERR_NO_ERROR 0


//the data length of a table header is too long(greater than 1M bytes)
#define ERR_NO_TABLE_HEADER_TOO_LONG 0x10000000

//the crc32 verify error of a table header structure.
#define ERR_TABLE_HEADER_CRC 0x20000001

//there are too many partitions in download header(greater than 0x1000 bytes).
#define ERR_DLH_TOO_MANY_PARTITIONS 0x30000000

//the file name in download header is too long(greater than 256 bytes).
#define ERR_DLH_TOO_LONG_FILE_NAME 0x30000001

//invalid manufacture code
#define ERR_DLH_INVALID_MANUFACTURE_CODE 0x30000002

//invalid hardware code
#define ERR_DLH_INVALID_HARDWARE_CODE 0x30000003

//too low uboot version to upgrade current upgrade image.
#define ERR_DLH_TOO_LOW_UBOOT_VERSION 0x30000004

//partition data crc32 verify error.
#define ERR_PARTITION_DATA_CRC 0x40000001

//unsupported signature arithmetic
#define ERR_UNSUPPORTED_SIGNATURE_ARITHMETIC 0x40000002

//read eeprom failed.
#define ERR_NVRAM_EEPROM_READ 0x50000001

//write eeprom failed.
#define ERR_NVRAM_EEPROM_WRITE 0x50000002

//erase SPI FLASH failed.
#define ERR_NVRAM_SPI_FLASH_ERASE 0x50000003

//write SPI FLASH failed.
#define ERR_NVRAM_SPI_FLASH_WRITE 0x50000004

//erase NAND FLASH failed.
#define ERR_NVRAM_NAND_FLASH_ERASE 0x50000005

//write NAND FLASH failed.
#define ERR_NVRAM_NAND_FLASH_WRITE 0x50000006

#endif
